import {
  pgTable,
  serial,
  text,
  timestamp,
  integer,
  boolean,
  real,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";

export const users = pgTable("users", {
  // Provider account id (Google's `sub`) — stable and deterministic.
  id: text("id").primaryKey(),
  email: text("email").notNull().unique(),
  name: text("name"),
  image: text("image"),
  provider: text("provider").notNull().default("google"),
  /**
   * The student's course / program (e.g. "BS Pharmacy"), chosen in the
   * first-login course picker. Free text: a known program from
   * src/lib/courses.ts or anything the user typed. Nullable until they
   * answer the picker — the AI prompt falls back to generic framing.
   */
  course: text("course"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

/**
 * Subject folders — an optional organisational layer above study sets.
 *
 * A subject is just a named bucket owned by one user; decks point at one with
 * `study_sessions.subject_id`. Deleting a subject leaves its decks in place
 * (the FK is `ON DELETE SET NULL`) — filing is metadata, never ownership.
 */
export const subjects = pgTable(
  "subjects",
  {
    id: serial("id").primaryKey(),
    /** Owner — every read/write is scoped to this column. */
    userId: text("user_id").notNull().references(() => users.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),
    /** Display name, unique per account so the picker list stays unambiguous. */
    name: text("name").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    // Two subjects with the same name for one user would make "move to
    // subject" ambiguous — the upsert-friendly key keeps them canonical.
    uniqueIndex("subjects_user_name_key").on(table.userId, table.name),
    index("subjects_user_id_idx").on(table.userId),
  ]
);

export const studySessions = pgTable(
  "study_sessions",
  {
    id: serial("id").primaryKey(),
    title: text("title").notNull(),
    sourceType: text("source_type").notNull(), // 'pdf' | 'image' | 'docx' | 'mixed' | 'text'
    sourceText: text("source_text"),
    /** 1-2 sentence description of the deck, generated by the AI. */
    summary: text("summary"),
    /**
     * Owner of the deck. Nullable for now so the migration is safe on
     * databases created before accounts existed; flip to notNull() once
     * legacy decks are adopted or purged.
     *
     * ON UPDATE cascade: when a sign-in re-keys a user row (same email,
     * new Google `sub` — see src/auth.ts), the decks follow automatically.
     */
    userId: text("user_id").references(() => users.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),
    /**
     * Optional subject folder this set is filed under (see `subjects`).
     * Null = the set lives directly in "All Sets". `ON DELETE SET NULL`
     * so removing a folder never deletes the sets inside it.
     */
    subjectId: integer("subject_id").references(() => subjects.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("study_sessions_created_at_idx").on(table.createdAt),
    index("study_sessions_user_id_idx").on(table.userId),
  ]
);

export const flashcards = pgTable(
  "flashcards",
  {
    id: serial("id").primaryKey(),
    sessionId: integer("session_id").notNull().references(() => studySessions.id, { onDelete: "cascade" }),
    question: text("question").notNull(),
    answer: text("answer").notNull(),
    hint: text("hint"),
    difficulty: text("difficulty").notNull().default("medium"), // 'easy' | 'medium' | 'hard'
    orderIndex: integer("order_index").notNull().default(0),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [index("flashcards_session_id_idx").on(table.sessionId)]
);

export const cardProgress = pgTable(
  "card_progress",
  {
    id: serial("id").primaryKey(),
    cardId: integer("card_id").notNull().references(() => flashcards.id, { onDelete: "cascade" }),
    sessionId: integer("session_id").notNull().references(() => studySessions.id, { onDelete: "cascade" }),
    isKnown: boolean("is_known").notNull().default(false),
    attempts: integer("attempts").notNull().default(0),
    lastReviewedAt: timestamp("last_reviewed_at").defaultNow(),
  },
  (table) => [
    // One progress row per (card, session) pair — makes upserts atomic and
    // the session-list "known" counts reliable.
    uniqueIndex("card_progress_card_session_key").on(table.cardId, table.sessionId),
    index("card_progress_session_id_idx").on(table.sessionId),
    index("card_progress_card_id_idx").on(table.cardId),
  ]
);

/**
 * Spaced-repetition scheduling state (P4) — one row per (user, card).
 *
 * `study_results` records *what happened*; this table records *when the card
 * should come back*. It is the persistence layer of `src/lib/srs.ts`, which
 * is the only thing allowed to compute the numbers below, so the algorithm
 * lives in exactly one place (and is unit-tested in scripts/srs.test.mjs).
 *
 * Keyed by (user_id, card_id): a card belongs to one deck, but keeping the
 * user in the key means a deck shared with somebody else could never leak
 * progress, and lets the "due now" queue be one indexed lookup per user.
 */
export const cardReviews = pgTable(
  "card_reviews",
  {
    id: serial("id").primaryKey(),
    /** Owner of the schedule — every read/write is scoped to this column. */
    userId: text("user_id").notNull().references(() => users.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),
    /** Deck the card belongs to (denormalized so deck filters stay cheap). */
    sessionId: integer("session_id").notNull().references(() => studySessions.id, { onDelete: "cascade" }),
    cardId: integer("card_id").notNull().references(() => flashcards.id, { onDelete: "cascade" }),
    /** SM-2 ease factor — clamped to [1.3, 2.8] by the scheduler. */
    ease: real("ease").notNull().default(2.5),
    /** Days until the next review; 0 = still on a sub-day learning step. */
    intervalDays: integer("interval_days").notNull().default(0),
    /** Consecutive successful reviews; resets to 0 on a lapse. */
    reps: integer("reps").notNull().default(0),
    /** Times the card was forgotten after graduating to review. */
    lapses: integer("lapses").notNull().default(0),
    /** Position in the learning/relearning steps while intervalDays = 0. */
    learningStep: integer("learning_step").notNull().default(0),
    /** Total grades applied to the card. */
    reviewCount: integer("review_count").notNull().default(0),
    /** Most recent grade: 'again' | 'hard' | 'good' | 'easy'. */
    lastGrade: text("last_grade"),
    lastReviewedAt: timestamp("last_reviewed_at"),
    /** When the card next becomes due. The review queue filters on this. */
    dueAt: timestamp("due_at").defaultNow().notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    // One schedule per (user, card) — makes the upsert atomic.
    uniqueIndex("card_reviews_user_card_key").on(table.userId, table.cardId),
    // "what's due for this user now" — the hot path of GET /api/review.
    index("card_reviews_user_due_idx").on(table.userId, table.dueAt),
    index("card_reviews_user_session_idx").on(table.userId, table.sessionId),
    index("card_reviews_card_id_idx").on(table.cardId),
  ]
);

/**
 * Presence heartbeats — one row per user, overwritten as they use the app.
 *
 * The owner's "who's online" roster (see src/lib/presence.ts and
 * GET /api/presence) is computed from this table alone: a user is online while
 * `last_seen_at` is younger than the online window (90 s, three missed
 * heartbeats at a 30 s cadence).
 *
 * Why a single upserted row instead of a session/event log:
 *   - the roster only ever asks "when was each user last seen?", which is one
 *     indexed row per account,
 *   - there is nothing to clean up — a closed tab simply stops refreshing
 *     `last_seen_at` and the user drops out of the window,
 *   - it stays tiny on serverless hosting (no sockets, no Redis).
 *
 * `user_id` is the primary key so the heartbeat is a single
 * `INSERT … ON CONFLICT (user_id) DO UPDATE`. Deleting a user cascades here,
 * and a sign-in that re-keys a user id (same email, new Google `sub`) follows
 * via ON UPDATE cascade.
 *
 * Caveat, on purpose: rows are *not* deleted when someone signs out — their
 * last-seen age is exactly what the owner wants to see.
 */
export const userPresence = pgTable(
  "user_presence",
  {
    userId: text("user_id")
      .primaryKey()
      .references(() => users.id, { onDelete: "cascade", onUpdate: "cascade" }),
    /** When this user last checked in (database clock, never the client's). */
    lastSeenAt: timestamp("last_seen_at").defaultNow().notNull(),
    /** Client-supplied label of what they were looking at — sanitised on write. */
    activity: text("activity"),
    /** Client-supplied coarse device label ("Chrome · macOS"). */
    device: text("device"),
  },
  (table) => [
    // "who was seen recently" — the roster's order-by, and cheap pruning later.
    index("user_presence_last_seen_idx").on(table.lastSeenAt),
  ]
);

export const studyResults = pgTable(
  "study_results",
  {
    id: serial("id").primaryKey(),
    /** Owner of the result — every read/write is scoped to this column. */
    userId: text("user_id").notNull().references(() => users.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),
    /** Deck (study_sessions row) the answered card belongs to. */
    sessionId: integer("session_id").notNull().references(() => studySessions.id, { onDelete: "cascade" }),
    /** The flashcard that was answered. */
    cardId: integer("card_id").notNull().references(() => flashcards.id, { onDelete: "cascade" }),
    /** Right/wrong signal — the foundation P4's spaced repetition consumes. */
    correct: boolean("correct").notNull(),
    /** Which mode produced the outcome: 'study' (self-check), 'exam' (MCQ), 'identify' (typed answer), 'enumerate' (listed items) or 'review' (spaced repetition). */
    mode: text("mode").notNull().default("study"),
    answeredAt: timestamp("answered_at").defaultNow().notNull(),
  },
  (table) => [
    index("study_results_user_id_idx").on(table.userId),
    index("study_results_session_id_idx").on(table.sessionId),
    index("study_results_card_id_idx").on(table.cardId),
    // Streaks + overall stats are per-user time-range queries.
    index("study_results_user_answered_idx").on(table.userId, table.answeredAt),
  ]
);

export type User = typeof users.$inferSelect;
export type Subject = typeof subjects.$inferSelect;
export type StudySession = typeof studySessions.$inferSelect;
export type Flashcard = typeof flashcards.$inferSelect;
export type CardProgress = typeof cardProgress.$inferSelect;
export type StudyResult = typeof studyResults.$inferSelect;
export type CardReview = typeof cardReviews.$inferSelect;

/** Push is strictly opt-in. Times are wall-clock times in an IANA zone. */
export const notificationPreferences = pgTable("notification_preferences", {
  userId: text("user_id").primaryKey().references(() => users.id, { onDelete: "cascade", onUpdate: "cascade" }),
  enabled: boolean("enabled").notNull().default(false),
  reminderTime: text("reminder_time").notNull().default("19:00"),
  timeZone: text("time_zone").notNull().default("UTC"),
  lastActiveAt: timestamp("last_active_at", { withTimezone: true }),
});

export const pushSubscriptions = pgTable("push_subscriptions", {
  id: serial("id").primaryKey(),
  userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade", onUpdate: "cascade" }),
  endpoint: text("endpoint").notNull().unique(),
  p256dh: text("p256dh").notNull(),
  auth: text("auth").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  lastTestAt: timestamp("last_test_at", { withTimezone: true }),
}, (t) => [index("push_subscriptions_user_idx").on(t.userId)]);

/** One daily reminder per account/local date, also visible in the inbox. */
export const notifications = pgTable("notifications", {
  id: serial("id").primaryKey(),
  userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade", onUpdate: "cascade" }),
  localDate: text("local_date").notNull(),
  dueCount: integer("due_count").notNull(),
  readAt: timestamp("read_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [uniqueIndex("notifications_user_day_key").on(t.userId, t.localDate), index("notifications_user_created_idx").on(t.userId, t.createdAt)]);

/** Durable per-device outbox: leases prevent concurrent cron sends. */
export const pushDeliveries = pgTable("push_deliveries", {
  id: serial("id").primaryKey(),
  notificationId: integer("notification_id").notNull().references(() => notifications.id, { onDelete: "cascade" }),
  subscriptionId: integer("subscription_id").notNull().references(() => pushSubscriptions.id, { onDelete: "cascade" }),
  status: text("status").notNull().default("pending"),
  attempts: integer("attempts").notNull().default(0),
  nextAttemptAt: timestamp("next_attempt_at", { withTimezone: true }).notNull().defaultNow(),
  leaseUntil: timestamp("lease_until", { withTimezone: true }),
  sentAt: timestamp("sent_at", { withTimezone: true }),
}, (t) => [uniqueIndex("push_deliveries_notice_device_key").on(t.notificationId, t.subscriptionId), index("push_deliveries_pending_idx").on(t.status, t.nextAttemptAt)]);
