import {
  pgTable,
  serial,
  text,
  timestamp,
  integer,
  boolean,
  real,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";

export const users = pgTable("users", {
  // Provider account id (Google's `sub`) — stable and deterministic.
  id: text("id").primaryKey(),
  email: text("email").notNull().unique(),
  name: text("name"),
  image: text("image"),
  provider: text("provider").notNull().default("google"),
  /**
   * The student's course / program (e.g. "BS Pharmacy"), chosen in the
   * first-login course picker. Free text: a known program from
   * src/lib/courses.ts or anything the user typed. Nullable until they
   * answer the picker — the AI prompt falls back to generic framing.
   */
  course: text("course"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const studySessions = pgTable(
  "study_sessions",
  {
    id: serial("id").primaryKey(),
    title: text("title").notNull(),
    sourceType: text("source_type").notNull(), // 'pdf' | 'image' | 'docx' | 'mixed' | 'text'
    sourceText: text("source_text"),
    /** 1-2 sentence description of the deck, generated by the AI. */
    summary: text("summary"),
    /**
     * Owner of the deck. Nullable for now so the migration is safe on
     * databases created before accounts existed; flip to notNull() once
     * legacy decks are adopted or purged.
     *
     * ON UPDATE cascade: when a sign-in re-keys a user row (same email,
     * new Google `sub` — see src/auth.ts), the decks follow automatically.
     */
    userId: text("user_id").references(() => users.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("study_sessions_created_at_idx").on(table.createdAt),
    index("study_sessions_user_id_idx").on(table.userId),
  ]
);

export const flashcards = pgTable(
  "flashcards",
  {
    id: serial("id").primaryKey(),
    sessionId: integer("session_id").notNull().references(() => studySessions.id, { onDelete: "cascade" }),
    question: text("question").notNull(),
    answer: text("answer").notNull(),
    hint: text("hint"),
    difficulty: text("difficulty").notNull().default("medium"), // 'easy' | 'medium' | 'hard'
    orderIndex: integer("order_index").notNull().default(0),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [index("flashcards_session_id_idx").on(table.sessionId)]
);

export const cardProgress = pgTable(
  "card_progress",
  {
    id: serial("id").primaryKey(),
    cardId: integer("card_id").notNull().references(() => flashcards.id, { onDelete: "cascade" }),
    sessionId: integer("session_id").notNull().references(() => studySessions.id, { onDelete: "cascade" }),
    isKnown: boolean("is_known").notNull().default(false),
    attempts: integer("attempts").notNull().default(0),
    lastReviewedAt: timestamp("last_reviewed_at").defaultNow(),
  },
  (table) => [
    // One progress row per (card, session) pair — makes upserts atomic and
    // the session-list "known" counts reliable.
    uniqueIndex("card_progress_card_session_key").on(table.cardId, table.sessionId),
    index("card_progress_session_id_idx").on(table.sessionId),
    index("card_progress_card_id_idx").on(table.cardId),
  ]
);

/**
 * Spaced-repetition scheduling state (P4) — one row per (user, card).
 *
 * `study_results` records *what happened*; this table records *when the card
 * should come back*. It is the persistence layer of `src/lib/srs.ts`, which
 * is the only thing allowed to compute the numbers below, so the algorithm
 * lives in exactly one place (and is unit-tested in scripts/srs.test.mjs).
 *
 * Keyed by (user_id, card_id): a card belongs to one deck, but keeping the
 * user in the key means a deck shared with somebody else could never leak
 * progress, and lets the "due now" queue be one indexed lookup per user.
 */
export const cardReviews = pgTable(
  "card_reviews",
  {
    id: serial("id").primaryKey(),
    /** Owner of the schedule — every read/write is scoped to this column. */
    userId: text("user_id").notNull().references(() => users.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),
    /** Deck the card belongs to (denormalized so deck filters stay cheap). */
    sessionId: integer("session_id").notNull().references(() => studySessions.id, { onDelete: "cascade" }),
    cardId: integer("card_id").notNull().references(() => flashcards.id, { onDelete: "cascade" }),
    /** SM-2 ease factor — clamped to [1.3, 2.8] by the scheduler. */
    ease: real("ease").notNull().default(2.5),
    /** Days until the next review; 0 = still on a sub-day learning step. */
    intervalDays: integer("interval_days").notNull().default(0),
    /** Consecutive successful reviews; resets to 0 on a lapse. */
    reps: integer("reps").notNull().default(0),
    /** Times the card was forgotten after graduating to review. */
    lapses: integer("lapses").notNull().default(0),
    /** Position in the learning/relearning steps while intervalDays = 0. */
    learningStep: integer("learning_step").notNull().default(0),
    /** Total grades applied to the card. */
    reviewCount: integer("review_count").notNull().default(0),
    /** Most recent grade: 'again' | 'hard' | 'good' | 'easy'. */
    lastGrade: text("last_grade"),
    lastReviewedAt: timestamp("last_reviewed_at"),
    /** When the card next becomes due. The review queue filters on this. */
    dueAt: timestamp("due_at").defaultNow().notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    // One schedule per (user, card) — makes the upsert atomic.
    uniqueIndex("card_reviews_user_card_key").on(table.userId, table.cardId),
    // "what's due for this user now" — the hot path of GET /api/review.
    index("card_reviews_user_due_idx").on(table.userId, table.dueAt),
    index("card_reviews_user_session_idx").on(table.userId, table.sessionId),
    index("card_reviews_card_id_idx").on(table.cardId),
  ]
);

/**
 * Presence heartbeats — one row per user, overwritten as they use the app.
 *
 * The owner's "who's online" roster (see src/lib/presence.ts and
 * GET /api/presence) is computed from this table alone: a user is online while
 * `last_seen_at` is younger than the online window (90 s, three missed
 * heartbeats at a 30 s cadence).
 *
 * Why a single upserted row instead of a session/event log:
 *   - the roster only ever asks "when was each user last seen?", which is one
 *     indexed row per account,
 *   - there is nothing to clean up — a closed tab simply stops refreshing
 *     `last_seen_at` and the user drops out of the window,
 *   - it stays tiny on serverless hosting (no sockets, no Redis).
 *
 * `user_id` is the primary key so the heartbeat is a single
 * `INSERT … ON CONFLICT (user_id) DO UPDATE`. Deleting a user cascades here,
 * and a sign-in that re-keys a user id (same email, new Google `sub`) follows
 * via ON UPDATE cascade.
 *
 * Caveat, on purpose: rows are *not* deleted when someone signs out — their
 * last-seen age is exactly what the owner wants to see.
 */
export const userPresence = pgTable(
  "user_presence",
  {
    userId: text("user_id")
      .primaryKey()
      .references(() => users.id, { onDelete: "cascade", onUpdate: "cascade" }),
    /** When this user last checked in (database clock, never the client's). */
    lastSeenAt: timestamp("last_seen_at").defaultNow().notNull(),
    /** Client-supplied label of what they were looking at — sanitised on write. */
    activity: text("activity"),
    /** Client-supplied coarse device label ("Chrome · macOS"). */
    device: text("device"),
  },
  (table) => [
    // "who was seen recently" — the roster's order-by, and cheap pruning later.
    index("user_presence_last_seen_idx").on(table.lastSeenAt),
  ]
);

export const studyResults = pgTable(
  "study_results",
  {
    id: serial("id").primaryKey(),
    /** Owner of the result — every read/write is scoped to this column. */
    userId: text("user_id").notNull().references(() => users.id, {
      onDelete: "cascade",
      onUpdate: "cascade",
    }),
    /** Deck (study_sessions row) the answered card belongs to. */
    sessionId: integer("session_id").notNull().references(() => studySessions.id, { onDelete: "cascade" }),
    /** The flashcard that was answered. */
    cardId: integer("card_id").notNull().references(() => flashcards.id, { onDelete: "cascade" }),
    /** Right/wrong signal — the foundation P4's spaced repetition consumes. */
    correct: boolean("correct").notNull(),
    /** Which mode produced the outcome: 'study' (self-check), 'exam' (MCQ), 'identify' (typed answer), 'enumerate' (listed items) or 'review' (spaced repetition). */
    mode: text("mode").notNull().default("study"),
    answeredAt: timestamp("answered_at").defaultNow().notNull(),
  },
  (table) => [
    index("study_results_user_id_idx").on(table.userId),
    index("study_results_session_id_idx").on(table.sessionId),
    index("study_results_card_id_idx").on(table.cardId),
    // Streaks + overall stats are per-user time-range queries.
    index("study_results_user_answered_idx").on(table.userId, table.answeredAt),
  ]
);

export type User = typeof users.$inferSelect;
export type StudySession = typeof studySessions.$inferSelect;
export type Flashcard = typeof flashcards.$inferSelect;
export type CardProgress = typeof cardProgress.$inferSelect;
export type StudyResult = typeof studyResults.$inferSelect;
export type CardReview = typeof cardReviews.$inferSelect;
